.TH gh 1 "02 Mar 2024" "0.1.0" "User commands"

.SH NAME
gh \- A minimal alternative to GitHub CLI.

.SH DESCRIPTION
gh is a CLI that works as an interface to github.com. It requires a browser for that and right now only Firefox is supported.

.SH SYNOPSIS
gh [COMMANDS] [OPTIONS]

.SH COMMANDS
.IP "gh-help"
Prints help.

.IP "gh-repo"
Open the repository page. When no option is provided, this command is used by default.

.IP "gh-pulls"
Open the pull request page of the current repository.

.SH GH-PULLS OPTIONS
.IP "--open"
Only list open pull requests.

.IP "--closed"
Only list closed pull requests.

.IP "--author=<value>"
Filter pull requests by author. `@me` works as an alis to your Github username.

.IP "--to-review"
Filter pull requests awaiting review from you.

.SH FILES
.TP
.I
~/.local/bin/gh
.TP
.I
~/.local/man/man1/gh.1.gz

.SH AUTHOR
Gustavo Ribeiro (grdev@tutanota.com)
